### PR TITLE
Oops!

### PR DESCRIPTION
**Pull request by wa4557**
I guess I pushed to upstream instead of origin, sorry :/

### CODE REVIEW

**Comment by wa4557** [comment]
I'm going to merge this, because I was messing with upstream instead of origin. This should be all Commits related to json

**Comment by bil-elmoussaoui** [comment]
Alright

**Comment by wa4557** [comment]
Everything should be fine now :)

**Comment by bil-elmoussaoui** [comment]
Perfect ! is teamviewer working now?

**Comment by wa4557** [comment]
Unfortunately not... Still no idea why, though

**Comment by bil-elmoussaoui** [comment]
Can you try the new PPA provided by @varlesh ? also check if there's any new sni-qt lib file that should be replaced

**Comment by wa4557** [comment]
Ok removing the file `libsni-qt.so` alltogether and the tray icon is still shown. I guess teamviewer is not using this file anymore

**Comment by wa4557** [comment]
Replacing any other Qt file didn't help though. Argh, we might have to replace the icons somewhere else...

**Comment by bil-elmoussaoui** [comment]
Or maybe just teamviewer use an other file on /usr/lib if the file does not exists?

**Comment by wa4557** [comment]
If teamviewer would use the files from system libraries the icon would be replaced though

**Comment by varlesh** [comment]
OMG! Program run on Wine, have 32-bit arch only and patched icons with sni-qt - it's crazy... :laughing: 
I hate some developers!

**Comment by varlesh** [comment]
And Electron-apps ugly, because this apps usage high RAM, have not native GUI on linux and hardcoded icons for tray...

Sorry for off-top ;)

**Comment by wa4557** [comment]
@varlesh Agree with everything you said, but people still using it :)

Yeah I fear the icon is hardcoded in the binary `TeamViewer.exe`, not sure though

**Comment by varlesh** [comment]
@wa4557 & @bil-elmoussaoui You good guys - you make Linux beauty!!!  Big thx for your work...
Maybe available native alternative for TeamViewer?

**Comment by wa4557** [comment]
I digged a bit deeper, and found out that there are these files `/opt/teamviewer/tv_bin/wine/drive_c/TeamViewer/TeamViewer_Resource_de.dll` where the icons are stored as `ico` files in the `dll` binary blob. No idea how to replace them though...

**Comment by bil-elmoussaoui** [comment]
Will check tomorrow if it's possible to modify the dll file without breaking anything

**Comment by bil-elmoussaoui** [comment]
But still can't understand the sni-qt icons stopped working in your case :( I think we might have to fork sni-qt from launchpad, patch it and release it

**Comment by wa4557** [comment]
Sni qt works (Skype for example) its just that TeamViewer doesnt use it anymore

**Pull request merged**
