### PR TITLE
Update script.py

### PR DESCRIPTION
**Pull request by wa4557**
I think the comments were mostly ok :)
My programming teacher always said: Good code doesn't need comments :P

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
As we both are the only ones who modify the script, the comments are unneeded :p as you've changed the comment from `real` to `correct` in `get_real_chrome..` can you change the function name too? :+1:

**Comment by bil-elmoussaoui** [comment]
Thanks!

**Comment by Foggalong** [comment]
Comments are always useful to have. If someone else comes along down the line and wants to contribute it makes it easier for them to understand what's going on

**Comment by bil-elmoussaoui** [comment]
:+1: That's why, i asked for someone to correct/update them

**Pull request merged**
