### PR TITLE
v3.9

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This PR should contain some code improvements and simplifications of overcomplicated stuff

What i want to be done before this going to be merged:
- [x] Split the electron module into two modules: asar and electron
- [x] use abstractmethod instead of using pass
- [x] Simplify settings, json & system files. Some methods shouldn't be static at all.
- [x] Verify that the icon theme detection works perfectly and improve it a little bit.

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Hey @wa4557, can you try this whenever you've got some free time? Everything works perfectly on my system. It's more on the continuation of code improvement as with the latest versions. And some small bug fixes

**Comment by wa4557** [comment]
I get an error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 878, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 870, in __missing__
    raise KeyError(key)
KeyError: 'gtk-icon-theme-name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hardcode-tray.py", line 87, in <module>
    if not isinstance(App.theme(), dict):
  File "/opt/Hardcode-Tray/src/app.py", line 168, in theme
    theme = App.get("theme")
  File "/opt/Hardcode-Tray/src/app.py", line 71, in get
    value = method()
  File "/opt/Hardcode-Tray/src/modules/config/system.py", line 77, in theme
    theme_name = cnfg.get("Settings", "gtk-icon-theme-name")
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gtk-icon-theme-name' in section: 'Settings'
```

**Comment by bil-elmoussaoui** [comment]
Alright, what distro/de are you using ?

**Comment by wa4557** [comment]
Ubuntu 16.04 / Unity

**Comment by bil-elmoussaoui** [comment]
Ah my bad, i thought that Unity stores the icon theme name  in https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/src/modules/config/system.py#L64

**Comment by bil-elmoussaoui** [comment]
Should be fixed

**Comment by wa4557** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 878, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 870, in __missing__
    raise KeyError(key)
KeyError: 'gtk-icon-theme-name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hardcode-tray.py", line 87, in <module>
    if not isinstance(App.theme(), dict):
  File "/opt/Hardcode-Tray/src/app.py", line 168, in theme
    theme = App.get("theme")
  File "/opt/Hardcode-Tray/src/app.py", line 71, in get
    value = method()
  File "/opt/Hardcode-Tray/src/modules/config/system.py", line 77, in theme
    theme_name = cnfg.get("Settings", "gtk-icon-theme-name")
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gtk-icon-theme-name' in section: 'Settings'
```

**Comment by bil-elmoussaoui** [comment]
Hmm, what's the output of `echo $XDG_CURRENT_DESKTOP`?

**Comment by wa4557** [comment]
`Unity`

**Comment by bil-elmoussaoui** [comment]
Hmm ! What if you add a print just after this line https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/beta/src/const.py#L43 to get the detected_desktop_env `print(DESKTOP_ENV)`

**Comment by wa4557** [comment]
Ah sorry my bad. It was using the installed version of the script :/

This is the error I get now:

```
  File "./hardcode-tray.py", line 104, in <module>
    App.execute()
  File "/home/andreas/Diverses/Hardcode-Tray/src/app.py", line 119, in execute
    delta = app.do_action(action)
  File "/home/andreas/Diverses/Hardcode-Tray/src/modules/applications/application.py", line 151, in do_action
    self.install()
  File "/home/andreas/Diverses/Hardcode-Tray/src/decorators.py", line 59, in wrapper
    func(app)
  File "/home/andreas/Diverses/Hardcode-Tray/src/modules/applications/application.py", line 97, in install
    self.execute(Action.APPLY)
  File "/home/andreas/Diverses/Hardcode-Tray/src/modules/applications/helpers/binary.py", line 51, in execute
    self.install_icon(icon, icon_path)
  File "/home/andreas/Diverses/Hardcode-Tray/src/modules/applications/electron.py", line 39, in install_icon
    png_bytes = get_pngbytes(icon)
  File "/home/andreas/Diverses/Hardcode-Tray/src/utils.py", line 242, in get_pngbytes
    App.icon_size())
  File "/home/andreas/Diverses/Hardcode-Tray/src/modules/svg/svg.py", line 90, in to_bin
    with open(outfile, 'rb') as temppng:
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/tmpej4c3bxt'

```

**Comment by wa4557** [comment]
Everything works fine :+1:

**Comment by bil-elmoussaoui** [comment]
Hmm, it shouldn't be any issue at all :( i will see what's going wrong. Anyway, it seems that the temporary output file is not found

**Comment by bil-elmoussaoui** [comment]
@wa4557 Should be fixed :)

**Comment by wa4557** [comment]
@bil-elmoussaoui Indeed everything works fine on two different machines :+1:

**Comment by bil-elmoussaoui** [comment]
Thanks for testing :+1:

**Pull request merged**
