### PR TITLE
Add new Telegram path

### LINKED ISSUE #335: Doesn't find Telegram
### Specifications
- Hardcode-Tray version : `3.6.6`
- Distribution : `Ubuntu 16.10`
- Application name :  `Telegram`
- Application version : `1.0.14`

I'm not sure what I'm doing wrong but hardcode-tray doesn't seems to find my Telegram install.

I have : 
`~App/Telegram` with `Telegram` and `Updater` and `~/.local/share/TelegramDesktop` with `tdata` and everything.

I tried using `--only telegram --path foobar` but nothing worked, always "No apps to fix!"

### PR DESCRIPTION
**Pull request by vayan**
See : https://github.com/telegramdesktop/tdesktop/issues/107#issuecomment-254517701

Fix #335

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
The app path shouldn't point to a folder, as it might be empty... the best way to fix this is to look for the Telegram binary file (maybe under /usr/bin?) or /opt/Telegram?

**Comment by vayan** [comment]
With the official install there's no install script or anything (from https://desktop.telegram.org/) you can extract the binaries anywhere. But maybe we can look for a specific file under `~/.local/share/TelegramDesktop/` ?

**Comment by bil-elmoussaoui** [comment]
Alright, can you do that please ? I'm using my phone for few days.. this way I can merge your PR as soon as possible

**Comment by vayan** [comment]
Done! I used the log file, created on every start of the app.

**Comment by bil-elmoussaoui** [comment]
Perfect! thanks, i will create a new release pretty soon :+1:

**Pull request merged**
