### PR TITLE
Handles problem when source and destination icons have different extensi...

### PR DESCRIPTION
**Pull request by wa4557**
...ons

I cleaned the code a little bit (removed global variables since they are not needed), and I added a way to handle pngs if the source theme has only svgs. Unfortunately this means that it's necessary to have `cairosvg` as a dependency since it converts the svgs to pngs

### CODE REVIEW

**Comment by wa4557** [comment]
I just saw that I changed all tabs to spaces . Sorry my editor does this by default. If you prefer tabs I can change it back...

**Comment by bil-elmoussaoui** [comment]
Well, thank you!! You just forgot a print in the deep_copy function :) Before i merge this, if the icon in the theme folder is svg and it's png in the hardcoded location; will it create a symlink ? or just convert the icon to png and then copy it?

**Comment by wa4557** [comment]
Symlink is not possible unfortunately, well because they are different files. It overwrites the hardcoded icon with a new png

**Comment by bil-elmoussaoui** [comment]
In deep_copy : print (o_file)

**Comment by wa4557** [comment]
Of course :)

**Comment by wa4557** [comment]
Cool!

**Comment by bil-elmoussaoui** [comment]
It's just getting better! For applications like telegram, we can't sadly use the same way, as the icons are generated automatically.

**Comment by wa4557** [comment]
Yeah telegram, google-chrome and skype are still problematic and not fixable imo

**Pull request merged**
