### PR TITLE
unpacks only once

### PR DESCRIPTION
**Pull request by wa4557**
Ok, it works now. Had a few problems because you switched from relative to absolute paths for the chrome script. 

Btw. Can you enlighten me, what the counter (`i`) in the get_apps_informations functions is for? Seems to be useless for me

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
well it was just to not read the first line, i had no idea how to do that :P as the first line in `db.csv` is just a description

**Comment by wa4557** [comment]
I see, but then a `r.next()` (to skip the line) would be better I guess, instead of this `if``else` clause. Plus your if else basically does nothing because `pass` doesn't do anything

**Comment by bil-elmoussaoui** [comment]
i will do that this evening

**Comment by bil-elmoussaoui** [comment]
Thanks!! You've removed a comment from `data_pack` is that fine?

**Comment by wa4557** [comment]
Yes, because we are not doing what is written there

**Pull request merged**
