### PR TITLE
WebTorrent Desktop fix

### PR DESCRIPTION
**Pull request by varlesh**
It's electron app, but asar unpacked (for icons only). For right work need use with `StartupWMClass=WebTorrent`, because desktop icon show as tray icon without WMClass...

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
I have been using WebTorrent Desktop for a while, and i have never notice a tray icon :o

**Comment by bil-elmoussaoui** [comment]
How did you enable that?

**Comment by varlesh** [comment]
i'm use your tool and seen your PR https://github.com/webtorrent/webtorrent-desktop/pull/1138

**Comment by bil-elmoussaoui** [comment]
Ah that wasn't a tray icon :o i'm using dash to panel,  and those are apps icons
WebTorrent is already supported by StartupWMClassFixer btw https://github.com/bil-elmoussaoui/StartupWMClassFixer/blob/master/database.csv#L68

**Comment by varlesh** [comment]
Yes, yes StartupWMClassFixer fix that )

**Comment by bil-elmoussaoui** [comment]
But it's isn't a Tray icon so :p this PR doesn't fix any tray icon at all

**Comment by varlesh** [comment]
No, it's tray icon, because on desktop file use another icon:
```
Name=WebTorrent
Version=1.0
GenericName=BitTorrent Client
X-GNOME-FullName=WebTorrent
Comment=Download and share files over BitTorrent
Encoding=UTF-8
Type=Application
Icon=webtorrent-desktop
Terminal=false
```
Icon=webtorrent-desktop

**Comment by varlesh** [comment]
Hardcode-tray + StartupWMClassFixer = fixed all. Why not?!

**Comment by bil-elmoussaoui** [comment]
Ah you're right! except this tray icon doesn't show up at all.. I just checked the source code and it's a tray icon.
Can you please add this location too ? `/usr/share/webtorrent-desktop/`
On archlinux, the files are not installed on /opt

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
ouh...
```
install -Dm644 "WebTorrent-linux-${_platform}/resources/app.asar.unpacked/static/WebTorrent.png" "${pkgdir}/usr/share/icons/hicolor/256x256/apps/${_pkgname}.png"
```

**Comment by bil-elmoussaoui** [comment]
It should work on Ubuntu https://github.com/webtorrent/webtorrent-desktop/blob/c764bf48841beb63c8820b3aaf568d3f0852ac75/src/main/tray.js#L109
As you can see on that file, they force to check that you're using Ubuntu or Debian & check if you have the libappindicator installed...

**Comment by varlesh** [comment]
On Ubuntu with Gnome all worked fine, but on Arch i don't know...
image

**Comment by bil-elmoussaoui** [comment]
It won't work on arch but thanks for the PR :+1:

**Comment by varlesh** [comment]
But libappindicator available from aur ... and not worked?

**Comment by bil-elmoussaoui** [comment]
@varlesh Read that comment on the code https://github.com/webtorrent/webtorrent-desktop/blob/c764bf48841beb63c8820b3aaf568d3f0852ac75/src/main/tray.js#L109

**Pull request merged**
