### PR TITLE
Modifies owncloud script

### PR DESCRIPTION
**Pull request by wa4557**
EDIT: I changed the owncloud script into a python script, because it allows better conversion from svg to png

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Much better indeed, i think that we should call the script something like qt-tray as it's the same location for all the qt applications?

**Comment by wa4557** [comment]
But then script.py needs to be changed as well. Why not just symlink this script to all the other names trat are needed?

**Comment by Foggalong** [comment]
Could add a new column to the main CSV called script which for each app is either blank or contains the name of the script needed to be run?

**Comment by wa4557** [comment]
@Foggalong I was wrong that's already possible right now (the third column is the script name)
@bil-elmoussaoui I'll change that accordingly!

**Comment by bil-elmoussaoui** [comment]
@Foggalong Can you try this now?

**Pull request merged**
