### PR TITLE
Update db.csv

### PR DESCRIPTION
**Pull request by wa4557**
The csv file needs a third (empty) row in order to be nice on github

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
It's unneeded for Google music manager

**Comment by wa4557** [comment]
Should I remove the third column then?

**Comment by bil-elmoussaoui** [comment]
Is this won't affect the script ? too lazy to try

**Comment by wa4557** [comment]
If it is unneeded for googlemusicmanager no I don't think so.

**Comment by wa4557** [comment]
But I guess it is needed, isn't it (line: 109 in script.py)

**Comment by bil-elmoussaoui** [comment]
i tested it , everything works fine and it's look better in Github

**Pull request merged**
