### PR TITLE
Minor PEP8 Fixes

### PR DESCRIPTION
**Pull request by Foggalong**

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
When i change the script file with the modifications you are proposing i'm having this new error message :(  
`script.py:13: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio
`

**Comment by Foggalong** [comment]
wait... you have to run that code before you finish importing modules!?

**Comment by bil-elmoussaoui** [comment]
Yes :( before importing the Gtk module

**Comment by Foggalong** [comment]
shoot, that totally breaks the PEP8 style guidelines :'( I've rearranged my code so that GTK imports fine, the modules remain grouped reasonably logically and the least number of PEP8 errors are thrown (just 1)

**Comment by bil-elmoussaoui** [comment]
Thanks !

**Pull request merged**
