### PR TITLE
Adds support for whatsie

### LINKED ISSUE #147: Whatsie support
There is a beautiful whatsapp wrapper on linux that creates a tray icon called whatsie. Unfortunately they use hardcoded tray icons :( 

https://github.com/Aluxian/Whatsie

I already opened a issue there asking for themable tray icons, but as far as I understand its currently not possible with the framework they are using (javascript / electron :o)

I guess the images are stored in a biinary file `/opt/whatsie/resources/app.asar` which is probably possible to unpack, I was, however, so far unable to do that...

@bil-elmoussaoui Any ideas?

### PR DESCRIPTION
**Pull request by wa4557**
Fixes #147 . I'm actually pretty proud about the coding I did here. No temporary files are necessary, everything is done on the fly, and I was able to introduce an iterative function :)

### CODE REVIEW

**Comment by wa4557** [comment]
@bil-elmoussaoui Do you fancy testing that, before I merge?

**Comment by bil-elmoussaoui** [comment]
Nice! :+1: We can now fix all the electron apps like Stremio, Gitter...

**Comment by wa4557** [comment]
I'm not so sure that this exact script will work for every `electron` app, since it requires the file to be in the exact same spot as for whatsie. But it should be an easy task to implement the same thing for other apps

**Comment by bil-elmoussaoui** [comment]
I have the same file on Stremio in the resources folder. Again, really nice work on this :dancer:

**Comment by wa4557** [comment]
Yeah but, this script only works if the png file is stored in the dictionary in key `['files']['images']['files'][icon_name]` I'm not so sure this is the same in stremio. 

Thanks, I guess I have to clean up the code a bit, but I like the fact that everything can be done on the fly and there are no temporary files necessary :)

**Comment by bil-elmoussaoui** [comment]
the `app.asar` is a binary file or a json one ? I will see if the images are stored on the same key on my side

**Comment by wa4557** [comment]
hmm they are some kind of strange archive, binary file. Haven't found a lot of information about them, and it took me quite some while to figure how to decode it. As far as I understand the file the information about the filesize, bnary offset and position in the file are stored in the header which is some kind of `json` file

**Pull request merged**
